---
- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Restart HAProxy
  systemd:
    name: haproxy
    state: restarted
  become: true