---
- name: Play Initial
  hosts: all
  become: true
  roles:
    - initial_setup

- name: Play Control Plane Primary
  hosts: control_plane_primary
  become: true
  roles:
    - microk8s_init

- name: Play Add Nodes Additional
  hosts: control_plane_additional
  become: true
  roles:
    - microk8s_join

- name: Play Deploy Services
  hosts: control_plane_primary
  become: true
  roles:
    - argocd
    - tekton

- name: Play Install and configure HAProxy
  hosts: haproxy
  become: true
  roles:
    - haproxy

- name: Play Test K8s
  hosts: control_plane_primary
  become: true
  roles:
    - sonobuoy
    - kube_bench
