---
- hosts: all
  become: yes
  roles:
    - basic_setup

- hosts: control_plane_primary
  become: yes
  roles:
    - microk8s_init

- hosts: control_plane_additional
  become: yes
  roles:
    - microk8s_add_control_plane

- hosts: workers
  become: yes
  roles:
    - microk8s_add_worker

- hosts: cluster_microk8s
  become: yes
  roles:
    - microk8s_hold_updates

- hosts: control_plane_primary
  become: yes
  roles:
    - argocd
#    - tekton

- hosts: control_plane_primary
  become: yes
  roles:
    - sonobuoy

- hosts: control_plane_primary
  become: yes
  roles:
    - kube_bench

- hosts: haproxy
  become: yes
  roles:
    - haproxy