---
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: yes

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    state: latest

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Allow the user to access kubeconfig
  command: /usr/bin/sudo chown -f -R {{ ansible_user }} ~/.kube

- name: Enable MicroK8s addons
  command: /snap/bin/microk8s enable dns dashboard ingress metallb storage rbac registry metrics-server
