---
- name: Wait for the secret of Argocd
  ansible.builtin.command: /snap/bin/microk8s kubectl get secret argocd-initial-admin-secret -n argocd
  register: argocd_secret_check
  changed_when: argocd_secret_check != 0
  until: argocd_secret_check == 0
  retries: 5
  delay: 10

- name: Obtain and decode the secret admin password of ArgoCD
  ansible.builtin.shell:
    cmd: set -o pipefail && kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode
    executable: /bin/bash
  register: admin_password_argocd
  changed_when: admin_password_argocd != 0

- name: Create ArgoCD ingress
  ansible.builtin.template:
    src: argocd-ingress.yaml.j2
    dest: /tmp/argocd-ingress.yaml
    mode: '0644'

- name: Apply ArgoCD ingress
  kubernetes.core.k8s:
    state: present
    src: "/tmp/argocd-ingress.yaml"
    namespace: argocd
  become: true

- name: Show ArgoCD initial admin password
  ansible.builtin.debug:
    msg: "ArgoCD initial admin password is: {{ admin_password_argocd.stdout }}"
