---
- name: Obtain and decode the secret admin password of ArgoCD
  ansible.builtin.shell:
    cmd: set -o pipefail && kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode
    executable: /bin/bash
  register: admin_password_argocd
  changed_when: admin_password_argocd != 0

- name: Create Argo CD ingress
  ansible.builtin.template:
    src: argocd-ingress.yaml.j2
    dest: /tmp/argocd-ingress.yaml
    mode: '0644'

- name: Apply Argo CD ingress
  kubernetes.core.k8s:
    state: present
    src: "/tmp/argocd-ingress.yaml"
    namespace: argocd
  become: true

- name: Show Argo CD initial admin password
  ansible.builtin.debug:
    msg: "Argo CD initial admin password is: {{ admin_password_argocd.stdout }}"
