---
- name: Create Argo CD namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
  ignore_errors: true
  become: true
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config

- name: Download Argo CD manifest
  get_url:
    url: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
    dest: "/tmp/argocd-install.yaml"
  become: true

- name: Apply Argo CD manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '/tmp/argocd-install.yaml') | from_yaml }}"
    namespace: argocd
  become: true
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config