---
- name: Deploy ArgoCD
  include_tasks: install.yml
  when: enable_argocd
  vars:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config

- name: Configure and Expose ArgoCD
  include_tasks: configure.yml
  when: enable_argocd
  vars:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config