---
# Vars DNS
nameservers:
  - 10.10.10.3
  - 8.8.8.8

fallback_dns:
  - 1.1.1.1
  - 1.0.0.1

resolved_conf_path: "/etc/systemd/resolved.conf"

# Vars NTP
ntp_servers:
  - "ntp.ubuntu.com"

# Versión Microk8s
microk8s_version: "1.30/stable"

# Networking Microk8s
enable_kube_ovn: true
pod_network_cidr: "10.16.0.0/16"
service_network_cidr: "10.96.0.0/12"
dns_ip: "10.96.0.10" 

# Extra IP and DNS for CERTS API
enable_extra_certs: true
load_balancer_ip: "10.10.10.16"
load_balancer_dns: "api-microk8s.arpovea.com"