---
- name: Download Kube-bench
  get_url:
    url: "https://github.com/aquasecurity/kube-bench/releases/download/v{{ kube_bench_version }}/kube-bench_{{ kube_bench_version }}_linux_amd64.tar.gz"
    dest: "/tmp/kube-bench.tar.gz"

- name: Extract Kube-bench
  unarchive:
    src: "/tmp/kube-bench.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes

- name: Ensure Kube-bench is executable
  file:
    path: "/usr/local/bin/kube-bench"
    mode: '0755'

- name: Download Kube-bench config archive
  get_url:
    url: "https://github.com/aquasecurity/kube-bench/archive/refs/heads/main.zip"
    dest: "/tmp/kube-bench-config.zip"

- name: Extract Kube-bench config archive
  unarchive:
    src: "/tmp/kube-bench-config.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Create directory for Kube-bench config
  file:
    path: "/usr/local/kube-bench/cfg"
    state: directory

- name: Copy Kube-bench config files
  copy:
    src: "/tmp/kube-bench-main/cfg"
    dest: "/usr/local/kube-bench/cfg"
    remote_src: yes
    
- name: Create directory for results on remote
  file:
    path: "/tmp/kube_bench_results"
    state: directory