---
- name: Download Kube-bench
  ansible.builtin.get_url:
    url: "https://github.com/aquasecurity/kube-bench/releases/download/v{{ kube_bench_version }}/kube-bench_{{ kube_bench_version }}_linux_amd64.tar.gz"
    dest: "/tmp/kube-bench.tar.gz"
    mode: '0644'

- name: Extract Kube-bench
  ansible.builtin.unarchive:
    src: "/tmp/kube-bench.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true

- name: Ensure Kube-bench is executable
  ansible.builtin.file:
    path: "/usr/local/bin/kube-bench"
    mode: '0755'

- name: Download Kube-bench config archive
  ansible.builtin.get_url:
    url: "https://github.com/aquasecurity/kube-bench/archive/refs/heads/main.zip"
    dest: "/tmp/kube-bench-config.zip"
    mode: '0644'

- name: Extract Kube-bench config archive
  ansible.builtin.unarchive:
    src: "/tmp/kube-bench-config.zip"
    dest: "/tmp/"
    remote_src: true

- name: Copy Kube-bench config files
  ansible.builtin.copy:
    src: "/tmp/kube-bench-main/cfg"
    dest: "/usr/local/kube-bench/"
    mode: '0755'
    remote_src: true

- name: Create directory for results on remote
  ansible.builtin.file:
    path: "/tmp/kube_bench_results"
    state: directory
    mode: '0755'
