---
- name: Download Kube-bench
  get_url:
    url: "https://github.com/aquasecurity/kube-bench/releases/download/v{{ kube_bench_version }}/kube-bench_{{ kube_bench_version }}_linux_amd64.tar.gz"
    dest: "/tmp/kube-bench.tar.gz"

- name: Extract Kube-bench
  unarchive:
    src: "/tmp/kube-bench.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes

- name: Ensure Kube-bench is executable
  file:
    path: "/usr/local/bin/kube-bench"
    mode: '0755'

- name: Download Kube-bench config files
  get_url:
    url: "https://raw.githubusercontent.com/aquasecurity/kube-bench/main/cfg/config.yaml"
    dest: "/tmp/config.yaml"
    remote_src: yes

- name: Create directory for Kube-bench config
  file:
    path: "/usr/local/kube-bench/cfg"
    state: directory

- name: Copy Kube-bench config file
  copy:
    src: "/tmp/config.yaml"
    dest: "/usr/local/kube-bench/cfg/config.yaml"
    remote_src: yes
