---
- name: Run Kube-bench
  command: "kube-bench run --config-dir /usr/local/kube-bench/cfg --config /usr/local/kube-bench/cfg/config.yaml --json --outputfile /tmp/kube_bench_results/kube-bench-results.json"

- name: Create directory for results on local
  local_action:
    module: file
    path: "./kube_bench_results"
    state: directory

- name: Fetch Kube-bench results to local machine
  fetch:
    src: "/tmp/kube_bench_results/kube-bench-results.json"
    dest: "./kube_bench_results/kube-bench-results.json"
    flat: true
