---
- name: Download Sonobuoy
  ansible.builtin.get_url:
    url: "https://github.com/vmware-tanzu/sonobuoy/releases/download/v{{ sonobuoy_version }}/sonobuoy_{{ sonobuoy_version }}_linux_amd64.tar.gz"
    dest: "/tmp/sonobuoy.tar.gz"
    mode: '0644'

- name: Extract Sonobuoy
  ansible.builtin.unarchive:
    src: "/tmp/sonobuoy.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true

- name: Ensure Sonobuoy is executable
  ansible.builtin.file:
    path: "/usr/local/bin/sonobuoy"
    mode: '0755'
