---
- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Create .kube directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Allow the user to access kubeconfig
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    recurse: yes

- name: Copy kubeconfig to the user's .kube directory
  command: microk8s config > {{ ansible_env.HOME }}/.kube/config
  become: yes
  become_user: "{{ ansible_user }}"