---
- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Allow the user to access kubeconfig
  command: /usr/bin/sudo chown -f -R {{ ansible_user }} ~/.kube
