---
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: true

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: true

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: true
    state: present


# Revisar repetición de la tarea install snapd