---
#  Definition of IP range for MetalLB
microk8s_init_metallb_ip_range: 10.10.10.150-10.10.10.160

# IP definition for ingress-controller (load balancer type)
microk8s_init_ip_ingress_controller: 10.10.10.151

# Install general addons on the first control plane

microk8s_init_addons:
  rbac: true
  metallb: false
  ingress: true
  metrics_server: true
  dashboard: true
  storage: false
  registry: false

microk8s_init_dashboard_host: "dashboard.arpovea.com"