---
#  Definition of IP range for MetalLB
metallb_ip_range: 10.10.10.150-10.10.10.160

# IP definition for ingress-controller (load balancer type)
ip_ingress_controller: 10.10.10.151

# Install general addons on the first control plane

addons:
  rbac: true
  metallb: false
  ingress: true
  metrics_server: true
  dashboard: true