---
- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes
  become: yes

- name: Create .kube directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Allow the user to access kubeconfig
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    recurse: yes
  become: yes

- name: Get MicroK8s kubeconfig
  command: /snap/bin/microk8s config
  register: microk8s_kubeconfig
  become: yes

- name: Write kubeconfig to the user's .kube directory
  copy:
    content: "{{ microk8s_kubeconfig.stdout }}"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    mode: '0644'
  become: yes
