---
- name: Enable MicroK8s DNS addon
  command: /snap/bin/microk8s enable dns

- name: Enable MicroK8s RBAC addon
  command: /snap/bin/microk8s enable rbac

- name: Enable MicroK8s MetalLB addon
  command: echo {{ metallb_ip_range }} | /snap/bin/microk8s enable metallb

- name: Wait for MetalLB namespace to be created
  command: /snap/bin/microk8s kubectl get ns metallb-system
  register: metallb_ns_check
  until: metallb_ns_check.rc == 0
  retries: 5
  delay: 10

- name: Configure MetalLB IP range
  template:
    src: metallb-config.yaml.j2
    dest: /tmp/metallb-config.yaml

- name: Apply MetalLB configuration
  command: /snap/bin/microk8s kubectl apply -f /tmp/metallb-config.yaml

- name: Enable MicroK8s Ingress addon
  command: /snap/bin/microk8s enable ingress  

- name: Create Ingress Controller Service
  template:
    src: ingress-controller-service.yaml.j2
    dest: /tmp/ingress-controller-service.yaml

- name: Apply Ingress Controller Service
  command: /snap/bin/microk8s kubectl apply -f /tmp/ingress-controller-service.yaml

- name: Enable MicroK8s Metrics Server addon
  command: /snap/bin/microk8s enable metrics-server

- name: Enable MicroK8s Dashboard addon
  command: /snap/bin/microk8s enable dashboard

#- name: Enable MicroK8s Storage addon
#  command: /snap/bin/microk8s enable storage

#- name: Enable MicroK8s Registry addon
#  command: /snap/bin/microk8s enable registry


