---
# Addon RBAC
- name: Enable MicroK8s RBAC addon
  ansible.builtin.command: /snap/bin/microk8s enable rbac
  register: addons_rbac
  changed_when: addons_rbac.rc != 0
  when: microk8s_init_addons.rbac
  become: true

# Addon MetalLB
- name: Enable MicroK8s MetalLB addon
  ansible.builtin.shell: 
    cmd: set -o pipefail && echo {{ metallb_ip_range }} | /snap/bin/microk8s enable metallb
    executable: /bin/bash
  register: addons_metallb
  changed_when: addons_metallb.rc != 0
  when: microk8s_init_addons.metallb
  become: true

- name: Wait for MetalLB namespace to be created
  ansible.builtin.command: /snap/bin/microk8s kubectl get ns metallb-system
  register: metallb_ns_check
  changed_when: metallb_ns_check.rc != 0
  until: metallb_ns_check.rc == 0
  retries: 5
  delay: 10
  when: microk8s_init_addons.metallb
  become: true

# Addon Ingress
- name: Enable MicroK8s Ingress addon
  ansible.builtin.command: /snap/bin/microk8s enable ingress
  register: addons_ingress
  changed_when: addons_ingress.rc != 0
  when: microk8s_init_addons.ingress
  become: true

- name: Create Ingress Controller Service
  ansible.builtin.template:
    src: ingress-controller-service.yaml.j2
    dest: /tmp/ingress-controller-service.yaml
    mode: '0644'
  when: microk8s_init_addons.ingress
  become: false

- name: Apply Ingress Controller Service
  ansible.builtin.command: /snap/bin/microk8s kubectl apply -f /tmp/ingress-controller-service.yaml
  register: addons_ingress_service
  changed_when: addons_ingress_service.rc != 0
  when: microk8s_init_addons.ingress
  become: true

# Addon Metrics Server
- name: Enable MicroK8s Metrics Server addon
  ansible.builtin.command: /snap/bin/microk8s enable metrics-server
  register: addons_metrics
  changed_when: addons_metrics.rc != 0
  when: microk8s_init_addons["metrics_server"]
  become: true

# Addon Dashboard
- name: Enable MicroK8s Dashboard addon
  ansible.builtin.command: /snap/bin/microk8s enable dashboard
  register: addons_dashboard
  changed_when: addons_dashboard.rc != 0
  when: microk8s_init_addons.dashboard
  become: true

# Addon Storage
- name: Enable MicroK8s Storage addon
  ansible.builtin.command: /snap/bin/microk8s enable storage
  register: addons_storage
  changed_when: addons_storage.rc != 0
  when: microk8s_init_addons.storage
  become: true

# Addon Registry
- name: Enable MicroK8s Registry addon
  ansible.builtin.command: /snap/bin/microk8s enable registry
  register: addons_registry
  changed_when: addons_registry.rc != 0
  when: microk8s_init_addons.registry
  become: true
