---
# Addon RBAC
- name: Enable MicroK8s RBAC addon
  command: /snap/bin/microk8s enable rbac
  when: addons.rbac

# Addon MetalLB
- name: Enable MicroK8s MetalLB addon
  shell: echo {{ metallb_ip_range }} | /snap/bin/microk8s enable metallb
  when: addons.metallb

- name: Wait for MetalLB namespace to be created
  command: /snap/bin/microk8s kubectl get ns metallb-system
  register: metallb_ns_check
  until: metallb_ns_check.rc == 0
  retries: 5
  delay: 10
  when: addons.metallb
  
# Addon Ingress
- name: Enable MicroK8s Ingress addon
  command: /snap/bin/microk8s enable ingress
  when: addons.ingress

- name: Create Ingress Controller Service
  template:
    src: ingress-controller-service.yaml.j2
    dest: /tmp/ingress-controller-service.yaml
  when: addons.ingress

- name: Apply Ingress Controller Service
  command: /snap/bin/microk8s kubectl apply -f /tmp/ingress-controller-service.yaml
  when: addons.ingress

# Addon Metrics Server
- name: Enable MicroK8s Metrics Server addon
  command: /snap/bin/microk8s enable metrics-server
  when: addons["metrics_server"]

# Addon Dashboard
- name: Enable MicroK8s Dashboard addon
  command: /snap/bin/microk8s enable dashboard
  when: addons.dashboard
## Mirar lo del rbac

# Addon Storage
- name: Enable MicroK8s Storage addon
  command: /snap/bin/microk8s enable storage
  when: addons.storage

# Addon Registry
- name: Enable MicroK8s Registry addon
  command: /snap/bin/microk8s enable registry
  when: addons.registry