---
- name: Wait for MicroK8s to be ready
  shell: "microk8s status --wait-ready"
  retries: 10
  delay: 10
  register: microk8s_status
  until: microk8s_status.rc == 0

- name: Generate MicroK8s join token
  command: /snap/bin/microk8s add-node --token-ttl 3600
  register: join_token_output
  become: yes

- name: Extract join token
  set_fact:
    microk8s_join_token: "{{ join_token_output.stdout | regex_search('microk8s join .*') | regex_replace('.*25000/', '') | regex_replace(' --.*', '') }}"