---
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: yes

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    state: present

# Hace falta para futuros roles (kube-bench)
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: yes
