---
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: true # Esto realmente es un bool es mejor utilizar true/false

- name: Ensure snapd is running # Revisar systemd por tema de deprecado
  service:
    name: snapd
    state: started
    enabled: true

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: true
    state: present

# Hace falta para futuros roles (kube-bench)
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: true

# Revisar tema de permisos Become, se hereda desde playbook, se puede especificar en false si quieres que una tarea concreta no se ejecute como sudo.