---
- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: yes

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    state: present
