---
- name: Enable MicroK8s Addons
  ansible.builtin.include_tasks: enable_addons.yml

- name: Generate Join token
  ansible.builtin.include_tasks: generate_token.yml

- name: Generate User Dashboard
  ansible.builtin.include_tasks: user_dashboard.yml
  when:
    - microk8s_init_addons.rbac
    - microk8s_init_addons.dashboard
