---
- name: Enable MicroK8s Addons
  include_tasks: enable_addons.yml

- name: Generate Join token
  include_tasks: generate_token.yml

- name: Generate User Dashboard
  include_tasks: user_dashboard.yml
  when:
    - addons.rbac
    - addons.dashboard
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config