---
- name: Create Tekton namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: tekton-pipelines

- name: Install Tekton using Argo CD Application
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: tekton-install
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://github.com/tektoncd/pipeline
          path: config
        destination:
          server: https://kubernetes.default.svc
          namespace: tekton-pipelines
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
