---
- name: Create Tekton namespace
  command: "/snap/bin/microk8s kubectl create namespace tekton-pipelines"
  ignore_errors: yes
  become: yes

- name: Download Tekton manifest
  get_url:
    url: "https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"
    dest: "/tmp/tekton-pipeline-release.yaml"
  become: yes

- name: Apply Tekton manifest
  command: "/snap/bin/microk8s kubectl apply -f /tmp/tekton-pipeline-release.yaml"
  become: yes