---
- name: Create Tekton namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: tekton-pipelines
  ignore_errors: true
  become: true
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config

- name: Download Tekton manifest
  get_url:
    url: "https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"
    dest: "/tmp/tekton-pipeline-release.yaml"
  become: true

- name: Apply Tekton manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', '/tmp/tekton-pipeline-release.yaml') | from_yaml }}"
    namespace: tekton-pipelines
  become: true