---
- name: Join the MicroK8s cluster as worker
  ansible.builtin.command: >
    /snap/bin/microk8s join
    {{ hostvars[groups['control_plane'][0]].ansible_host }}:25000/
    {{ hostvars[groups['control_plane'][0]].microk8s_join_token }} --worker
  register: join_extra_worker
  changed_when: join_extra_worker.rc != 0
  when: "'node/' + inventory_hostname not in hostvars[groups['control_plane'][0]].existing_nodes"
  become: true
