---
- name: Join the MicroK8s cluster as control plane
  ansible.builtin.include_tasks: join_cluster_cp.yml
  when: "'control_plane_additional' in group_names"

- name: Join the MicroK8s cluster as worker
  ansible.builtin.include_tasks: join_cluster_worker.yml
  when: "'workers' in group_names"
