---
- name: Play Initial
  hosts: all
  become: true
  roles:
    - basic_setup

- name: Play Control Plane Primary
  hosts: control_plane_primary
  become: true
  roles:
    - microk8s_init

- name: Play Add Control plane Additional
  hosts: control_plane_additional
  become: true
  roles:
    - microk8s_add_control_plane

- name: Play Add Workers
  hosts: workers
  become: true
  roles:
    - microk8s_add_worker

- name: Play Deploy Services
  hosts: control_plane_primary
  become: true
  roles:
    - argocd
    - tekton

- name: Play Hold Updates
  hosts: cluster_microk8s
  become: true
  roles:
    - microk8s_hold_updates

- name: Play Install and configure HAProxy
  hosts: haproxy
  become: true
  roles:
    - haproxy

- name: Play Test K8s
  hosts: control_plane_primary
  become: true
  roles:
    - sonobuoy
    - kube_bench
