---
- name: Delete previously key
  shell: rm -rf /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Delete previously repolist
  shell: rm -rf /etc/apt/sources.list.d/kubernetes.list
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Update apt cache and upgrade packages
  apt:
    update_cache: true
    upgrade: true
  become: true

# Kubectl

- name: Instalar dependencias
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Delete previously key
  shell: rm -rf /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Download the public signing key for Kubernetes and Convert the key to a GPG keyring format
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Set permissions for the signing key
  file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Add the Kubernetes apt repository
  shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' |  tee /etc/apt/sources.list.d/kubernetes.list
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Install kubectl
  apt:
    name: kubectl
    state: present
  when: "'cluster_microk8s' in group_names"
  become: true

- name: Mantener kubectl en la versión actual para evitar actualizaciones automáticas
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold
  become: true
  when: "'cluster_microk8s' in group_names"

# Necesario para kube-bench
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: true
  when: "'control_plane_primary' in group_names"

# Necesario para el módulo de k8s

## Asegurar la instalación de Python y Pip
- name: Ensure Python 3 is installed
  apt:
    name: python3
    state: present
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure Pip for Python 3 is installed
  apt:
    name: python3-pip
    state: present
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure setuptools is installed via pip
  pip:
    name: setuptools
    state: present
    executable: pip3
  become: true
  when: "'cluster_microk8s' in group_names"

## Instalar las bibliotecas de Python necesarias
- name: Ensure kubernetes library is installed
  pip:
    name: kubernetes
    version: '>=24.2.0'
    executable: pip3
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure PyYAML library is installed
  pip:
    name: PyYAML
    version: '>=3.11'
    executable: pip3
  become: true
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Crear lista de servidores DNS como una cadena
  set_fact:
    dns_servers: "{{ nameservers | join(' ') }}"
    fallback_dns_servers: "{{ fallback_dns | join(' ') }}"

- name: Configurar servidores DNS en /etc/systemd/resolved.conf
  blockinfile:
    path: "{{ resolved_conf_path }}"
    block: |
      [Resolve]
      DNS={{ dns_servers }}
      FallbackDNS={{ fallback_dns_servers }}
      DNSStubListener=yes
  become: true

- name: Asegurarse de que systemd-resolved esté habilitado y reiniciado
  systemd:
    name: systemd-resolved
    enabled: true
    state: restarted
  become: true

- name: Install chrony for time synchronization
  apt:
    name: chrony
    state: present
  become: true

- name: Configure NTP servers
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure chrony is running
  systemd:
    name: chrony
    enabled: true
    state: restarted
  become: true
