---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: true
    upgrade: true
  become: true

# Necesario para kube-bench
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: true
  when: "'control_plane_primary' in group_names"

# Necesario para el módulo de k8s

## Asegurar la instalación de Python y Pip
- name: Ensure Python 3 is installed
  apt:
    name: python3
    state: present
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure Pip for Python 3 is installed
  apt:
    name: python3-pip
    state: present
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure setuptools is installed via pip
  pip:
    name: setuptools
    state: present
    executable: pip3
  become: true
  when: "'cluster_microk8s' in group_names"

## Instalar las bibliotecas de Python necesarias
- name: Ensure kubernetes library is installed
  pip:
    name: kubernetes
    version: '>=24.2.0'
    executable: pip3
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure PyYAML library is installed
  pip:
    name: PyYAML
    version: '>=3.11'
    executable: pip3
  become: true
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Crear lista de servidores DNS como una cadena
  set_fact:
    dns_servers: "{{ nameservers | join(' ') }}"
    fallback_dns_servers: "{{ fallback_dns | join(' ') }}"

- name: Configurar servidores DNS en /etc/systemd/resolved.conf
  blockinfile:
    path: "{{ resolved_conf_path }}"
    block: |
      [Resolve]
      DNS={{ dns_servers }}
      FallbackDNS={{ fallback_dns_servers }}
      DNSStubListener=yes
  become: true

- name: Asegurarse de que systemd-resolved esté habilitado y reiniciado
  systemd:
    name: systemd-resolved
    enabled: true
    state: restarted
  become: true

- name: Install chrony for time synchronization
  apt:
    name: chrony
    state: present
  become: true

- name: Configure NTP servers
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure chrony is running
  systemd:
    name: chrony
    enabled: true
    state: restarted
  become: true
