---
- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true

# Required for kube-bench
- name: Ensure unzip is installed
  ansible.builtin.apt:
    name: unzip
    state: present
  become: true
  when: "'control_plane_primary' in group_names"

# Required for k8s module

## Installing Python and Pip
- name: Ensure Python 3 is installed
  ansible.builtin.apt:
    name: python3
    state: present
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure Pip for Python 3 is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure setuptools is installed via pip
  ansible.builtin.pip:
    name: setuptools
    state: present
    executable: pip3
  become: true
  when: "'cluster_microk8s' in group_names"

## Install the necessary Python libraries
- name: Ensure kubernetes library is installed
  ansible.builtin.pip:
    name: kubernetes
    version: '>=24.2.0'
    executable: pip3
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Ensure PyYAML library is installed
  ansible.builtin.pip:
    name: PyYAML
    version: '>=3.11'
    executable: pip3
  become: true

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true
  when: "'cluster_microk8s' in group_names"

- name: Create DNS server list as a string
  ansible.builtin.set_fact:
    dns_servers: "{{ initial_setup_nameservers | join(' ') }}"
    fallback_dns_servers: "{{ initial_setup_fallback_dns | join(' ') }}"

- name: Configuring DNS servers in /etc/systemd/resolved.conf
  ansible.builtin.blockinfile:
    path: "{{ initial_setup_resolved_conf_path }}"
    block: |
      [Resolve]
      DNS={{ dns_servers }}
      FallbackDNS={{ fallback_dns_servers }}
      DNSStubListener=yes
  become: true

- name: Ensure that systemd-resolved is enabled and restarted
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    state: restarted
  become: true

- name: Install chrony for time synchronization
  ansible.builtin.apt:
    name: chrony
    state: present
  become: true

- name: Configure NTP servers
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Ensure chrony is running
  ansible.builtin.systemd:
    name: chrony
    enabled: true
    state: restarted
  become: true
