
---
- name: Check if MicroK8s is installed
  command: /snap/bin/microk8s status --wait-ready
  register: microk8s_status
  failed_when: false
  changed_when: false

- name: Create the configuration directory
  file:
    path: /var/snap/microk8s/common
    state: directory
    mode: '0755'
  become: true
  when: microk8s_status.rc != 0
  
- name: Copy the launch configuration file
  template:
    src: microk8s-config.yaml.j2
    dest: /var/snap/microk8s/common/.microk8s.yaml
    mode: '0644'
  become: true
  when: microk8s_status.rc != 0

- name: Ensure snapd is running
  systemd:
    name: snapd
    state: started
    enabled: true
  become: true
  when: microk8s_status.rc != 0

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: true
    state: present
  channel: "{{ microk8s_version }}"
  become: true
  when: microk8s_status.rc != 0

- name: Hold Snap packages to prevent automatic updates
  command: snap refresh --hold microk8s
  become: true
  when: microk8s_status.rc != 0

- name: Disable kube-ovn
  command: /snap/bin/microk8s disable kube-ovn
  changed_when: false
  register: disable_kube_ovn_result
  become: true

- name: Restart MicroK8s to apply configuration changes
  command: /snap/bin/microk8s stop && /snap/bin/microk8s start
  when: disable_kube_ovn_result is changed
  become: true

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: true
  become: true

- name: Create kubectl alias
  become: true
  command: "snap alias microk8s.kubectl kubectl"
  changed_when: false
  register: aliaskubectlout
