
---
- name: Ensure snapd is running
  systemd:
    name: snapd
    state: started
    enabled: true
  become: true

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: true
    state: present
  become: true

- name: Hold Snap packages to prevent automatic updates
  command: snap refresh --hold microk8s
  become: true

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: true
  become: true
  when: "'control_plane' in group_names"

- name: Create .kube directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  become: true
  when: "'control_plane' in group_names"

- name: Allow the user to access kubeconfig
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    recurse: true
  become: true
  when: "'control_plane' in group_names"

# Necesario para kube-bench
- name: Ensure unzip is installed
  apt:
    name: unzip
    state: present
  become: true
  when: "'control_plane_primary' in group_names"